[project]
name = "jespers-uppgift"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.0",
    "mitsuba==3.5.2",
    "numpy>=2.0.2",
    "tensorflow>=2.18.0",
]
